name: Deploy
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/deploy.yml
      - "*.tf"
  workflow_dispatch:

defaults:
  run:
    shell: bash -exuo pipefail {0}

env:
  FLUXCD_VERSION: 2.0.0-rc.1
  GCP_SERVICE_ACCOUNT: infrastructure@arik-kfir.iam.gserviceaccount.com
  GCP_WORKLOAD_IDENTITY_PROVIDER: projects/887552287733/locations/global/workloadIdentityPools/github-actions/providers/default
  GCP_CLI_VERSION: 426.0.0
  TERRAFORM_VERSION: 1.4.3
  TF_IN_AUTOMATION: true

concurrency:
  group: production
  cancel-in-progress: false

permissions:
  id-token: write

jobs:

  plan-terraform:
    name: Plan Terraform
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}
      - uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ env.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ env.GCP_SERVICE_ACCOUNT }}
      - uses: google-github-actions/setup-gcloud@v1
        with:
          version: ${{ env.GCP_CLI_VERSION }}
      - run: |
          terraform fmt -check -recursive -no-color -diff
          terraform init -input=false
          terraform plan -input=false -lock-timeout=180s -out tfplan
          tar -c -j -v -f tfplan.tar.bz2 .terraform .terraform.lock.hcl *.tf tfplan
      - uses: actions/upload-artifact@v3
        with:
          name: plan
          path: tfplan.tar.bz2
          if-no-files-found: error
          retention-days: 1

  apply-terraform:
    name: Apply Terraform
    needs: plan-terraform
    runs-on: ubuntu-latest
    timeout-minutes: 120
    environment: production
    outputs:
      main-gke-cluster-name: ${{ steps.apply.outputs.main-gke-cluster-name }}
      main-gke-cluster-location: ${{ steps.apply.outputs.main-gke-cluster-location }}
      arc-gke-cluster-name: ${{ steps.apply.outputs.arc-gke-cluster-name }}
      arc-gke-cluster-location: ${{ steps.apply.outputs.arc-gke-cluster-location }}
    steps:
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}
          terraform_wrapper: false
      - uses: actions/download-artifact@v3
        with:
          name: plan
      - uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ env.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ env.GCP_SERVICE_ACCOUNT }}
      - uses: google-github-actions/setup-gcloud@v1
        with:
          install_components: gke-gcloud-auth-plugin
          version: ${{ env.GCP_CLI_VERSION }}
      - run: |
          tar xjvf tfplan.tar.bz2
          terraform apply -input=false -lock-timeout=180s -auto-approve tfplan
          echo "main-gke-cluster-name=$(terraform output -raw main_gke_cluster_name)" >> $GITHUB_OUTPUT
          echo "main-gke-cluster-location=$(terraform output -raw main_gke_cluster_location)" >> $GITHUB_OUTPUT
          echo "arc-gke-cluster-name=$(terraform output -raw arc_gke_cluster_name)" >> $GITHUB_OUTPUT
          echo "arc-gke-cluster-location=$(terraform output -raw arc_gke_cluster_location)" >> $GITHUB_OUTPUT
        id: apply

  apply-main-fluxcd:
    name: Apply FluxCD in "main"
    needs: apply-terraform
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ env.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ env.GCP_SERVICE_ACCOUNT }}
      - uses: google-github-actions/setup-gcloud@v1
        with:
          version: ${{ env.GCP_CLI_VERSION }}
      - uses: google-github-actions/get-gke-credentials@v0
        with:
          cluster_name: ${{ needs.apply-terraform.outputs.main-gke-cluster-name }}
          location: ${{ needs.apply-terraform.outputs.main-gke-cluster-location }}
      - uses: fluxcd/flux2/action@main
        with:
          version: ${{ env.FLUXCD_VERSION }}
      - run: |
          flux bootstrap github \
            --interval 5m \
            --owner arik-kfir \
            --repository delivery \
            --branch main \
            --path clusters/${GKE_CLUSTER_NAME} \
            --personal \
            --reconcile \
            --author-email flux@kfirs.com \
            --author-name "FluxCD Bot" \
            --timeout 30m \
            --version=v2.0.0-rc.1
        env:
          GKE_CLUSTER_NAME: ${{ needs.apply-terraform.outputs.main-gke-cluster-name }}
          GITHUB_TOKEN: ${{ secrets.FLUXCD_PAT }}

  apply-arc-fluxcd:
    name: Apply FluxCD in "arc"
    needs: apply-terraform
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ env.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ env.GCP_SERVICE_ACCOUNT }}
      - uses: google-github-actions/setup-gcloud@v1
        with:
          version: ${{ env.GCP_CLI_VERSION }}
      - uses: google-github-actions/get-gke-credentials@v0
        with:
          cluster_name: ${{ needs.apply-terraform.outputs.arc-gke-cluster-name }}
          location: ${{ needs.apply-terraform.outputs.arc-gke-cluster-location }}
      - uses: fluxcd/flux2/action@main
        with:
          version: ${{ env.FLUXCD_VERSION }}
      - run: |
          flux bootstrap github \
            --interval 5m \
            --owner arik-kfir \
            --repository delivery \
            --branch main \
            --path clusters/${GKE_CLUSTER_NAME} \
            --personal \
            --reconcile \
            --author-email flux@kfirs.com \
            --author-name "FluxCD Bot" \
            --timeout 30m \
            --version=v2.0.0-rc.1
        env:
          GKE_CLUSTER_NAME: ${{ needs.apply-terraform.outputs.arc-gke-cluster-name }}
          GITHUB_TOKEN: ${{ secrets.FLUXCD_PAT }}
