name: GKE Garbage Collector

on:
  schedule:
    - cron: "0 * * * *"

defaults:
  run:
    shell: bash -exuo pipefail {0}

env:
  GCP_SERVICE_ACCOUNT: infrastructure@arik-kfir.iam.gserviceaccount.com
  GCP_WORKLOAD_IDENTITY_PROVIDER: projects/887552287733/locations/global/workloadIdentityPools/github-actions/providers/default
  GCP_CLI_VERSION: 426.0.0
  GCP_REGION: me-west1
  GKE_CLUSTER_NAME: main
  GKE_CLUSTER_LOCATION: me-west1-a

concurrency:
  group: production
  cancel-in-progress: false

jobs:

  gc:
    name: Garbage Collect
    runs-on: self-hosted
    timeout-minutes: 5
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ env.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ env.GCP_SERVICE_ACCOUNT }}
      - uses: google-github-actions/setup-gcloud@v1
        with:
          version: ${{ env.GCP_CLI_VERSION }}
      - uses: google-github-actions/get-gke-credentials@v0
        with:
          cluster_name: ${{ env.GKE_CLUSTER_NAME }}
          location: ${{ env.GKE_CLUSTER_LOCATION }}
      - run: kubectl get pods --all-namespaces | grep -i shutdown | awk '{print $1, $2}' | xargs -n2 kubectl delete pod -n
